/**
 * Autogenerated by Thrift Compiler (0.14.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.apache.spark.scheduler.rpc;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.14.2)", date = "2024-01-26")
public class Request1 implements org.apache.thrift.TBase<Request1, Request1._Fields>, java.io.Serializable, Cloneable, Comparable<Request1> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Request1");

  private static final org.apache.thrift.protocol.TField NUM_MAPPERS_FIELD_DESC = new org.apache.thrift.protocol.TField("numMappers", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField NUM_REDUCERS_FIELD_DESC = new org.apache.thrift.protocol.TField("numReducers", org.apache.thrift.protocol.TType.I32, (short)2);
  private static final org.apache.thrift.protocol.TField NUM_SITES_FIELD_DESC = new org.apache.thrift.protocol.TField("numSites", org.apache.thrift.protocol.TType.I32, (short)3);
  private static final org.apache.thrift.protocol.TField BANDWIDTH_FIELD_DESC = new org.apache.thrift.protocol.TField("bandwidth", org.apache.thrift.protocol.TType.LIST, (short)4);
  private static final org.apache.thrift.protocol.TField FINISH_TIME_FIELD_DESC = new org.apache.thrift.protocol.TField("finishTime", org.apache.thrift.protocol.TType.LIST, (short)5);
  private static final org.apache.thrift.protocol.TField OUTPUT_SIZE_FIELD_DESC = new org.apache.thrift.protocol.TField("outputSize", org.apache.thrift.protocol.TType.LIST, (short)6);
  private static final org.apache.thrift.protocol.TField SITE_LOAD_FIELD_DESC = new org.apache.thrift.protocol.TField("siteLoad", org.apache.thrift.protocol.TType.LIST, (short)7);
  private static final org.apache.thrift.protocol.TField ASSIGN_FIELD_DESC = new org.apache.thrift.protocol.TField("assign", org.apache.thrift.protocol.TType.LIST, (short)8);
  private static final org.apache.thrift.protocol.TField ALPHA_FIELD_DESC = new org.apache.thrift.protocol.TField("alpha", org.apache.thrift.protocol.TType.DOUBLE, (short)9);
  private static final org.apache.thrift.protocol.TField SITE_SLOTS_FIELD_DESC = new org.apache.thrift.protocol.TField("siteSlots", org.apache.thrift.protocol.TType.LIST, (short)10);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new Request1StandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new Request1TupleSchemeFactory();

  public int numMappers; // required
  public int numReducers; // required
  public int numSites; // required
  public @org.apache.thrift.annotation.Nullable java.util.List<java.util.List<java.lang.Integer>> bandwidth; // optional
  public @org.apache.thrift.annotation.Nullable java.util.List<java.util.List<java.lang.Integer>> finishTime; // optional
  public @org.apache.thrift.annotation.Nullable java.util.List<java.util.List<java.util.List<java.lang.Long>>> outputSize; // optional
  public @org.apache.thrift.annotation.Nullable java.util.List<java.lang.Double> siteLoad; // optional
  public @org.apache.thrift.annotation.Nullable java.util.List<java.lang.Integer> assign; // optional
  public double alpha; // required
  public @org.apache.thrift.annotation.Nullable java.util.List<java.lang.Integer> siteSlots; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    NUM_MAPPERS((short)1, "numMappers"),
    NUM_REDUCERS((short)2, "numReducers"),
    NUM_SITES((short)3, "numSites"),
    BANDWIDTH((short)4, "bandwidth"),
    FINISH_TIME((short)5, "finishTime"),
    OUTPUT_SIZE((short)6, "outputSize"),
    SITE_LOAD((short)7, "siteLoad"),
    ASSIGN((short)8, "assign"),
    ALPHA((short)9, "alpha"),
    SITE_SLOTS((short)10, "siteSlots");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // NUM_MAPPERS
          return NUM_MAPPERS;
        case 2: // NUM_REDUCERS
          return NUM_REDUCERS;
        case 3: // NUM_SITES
          return NUM_SITES;
        case 4: // BANDWIDTH
          return BANDWIDTH;
        case 5: // FINISH_TIME
          return FINISH_TIME;
        case 6: // OUTPUT_SIZE
          return OUTPUT_SIZE;
        case 7: // SITE_LOAD
          return SITE_LOAD;
        case 8: // ASSIGN
          return ASSIGN;
        case 9: // ALPHA
          return ALPHA;
        case 10: // SITE_SLOTS
          return SITE_SLOTS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __NUMMAPPERS_ISSET_ID = 0;
  private static final int __NUMREDUCERS_ISSET_ID = 1;
  private static final int __NUMSITES_ISSET_ID = 2;
  private static final int __ALPHA_ISSET_ID = 3;
  private byte __isset_bitfield = 0;
  private static final _Fields optionals[] = {_Fields.BANDWIDTH,_Fields.FINISH_TIME,_Fields.OUTPUT_SIZE,_Fields.SITE_LOAD,_Fields.ASSIGN};
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.NUM_MAPPERS, new org.apache.thrift.meta_data.FieldMetaData("numMappers", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.NUM_REDUCERS, new org.apache.thrift.meta_data.FieldMetaData("numReducers", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.NUM_SITES, new org.apache.thrift.meta_data.FieldMetaData("numSites", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.BANDWIDTH, new org.apache.thrift.meta_data.FieldMetaData("bandwidth", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
                new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)))));
    tmpMap.put(_Fields.FINISH_TIME, new org.apache.thrift.meta_data.FieldMetaData("finishTime", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
                new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)))));
    tmpMap.put(_Fields.OUTPUT_SIZE, new org.apache.thrift.meta_data.FieldMetaData("outputSize", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
                new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
                    new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64))))));
    tmpMap.put(_Fields.SITE_LOAD, new org.apache.thrift.meta_data.FieldMetaData("siteLoad", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE))));
    tmpMap.put(_Fields.ASSIGN, new org.apache.thrift.meta_data.FieldMetaData("assign", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32))));
    tmpMap.put(_Fields.ALPHA, new org.apache.thrift.meta_data.FieldMetaData("alpha", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE)));
    tmpMap.put(_Fields.SITE_SLOTS, new org.apache.thrift.meta_data.FieldMetaData("siteSlots", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32))));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Request1.class, metaDataMap);
  }

  public Request1() {
  }

  public Request1(
    int numMappers,
    int numReducers,
    int numSites,
    double alpha,
    java.util.List<java.lang.Integer> siteSlots)
  {
    this();
    this.numMappers = numMappers;
    setNumMappersIsSet(true);
    this.numReducers = numReducers;
    setNumReducersIsSet(true);
    this.numSites = numSites;
    setNumSitesIsSet(true);
    this.alpha = alpha;
    setAlphaIsSet(true);
    this.siteSlots = siteSlots;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public Request1(Request1 other) {
    __isset_bitfield = other.__isset_bitfield;
    this.numMappers = other.numMappers;
    this.numReducers = other.numReducers;
    this.numSites = other.numSites;
    if (other.isSetBandwidth()) {
      java.util.List<java.util.List<java.lang.Integer>> __this__bandwidth = new java.util.ArrayList<java.util.List<java.lang.Integer>>(other.bandwidth.size());
      for (java.util.List<java.lang.Integer> other_element : other.bandwidth) {
        java.util.List<java.lang.Integer> __this__bandwidth_copy = new java.util.ArrayList<java.lang.Integer>(other_element);
        __this__bandwidth.add(__this__bandwidth_copy);
      }
      this.bandwidth = __this__bandwidth;
    }
    if (other.isSetFinishTime()) {
      java.util.List<java.util.List<java.lang.Integer>> __this__finishTime = new java.util.ArrayList<java.util.List<java.lang.Integer>>(other.finishTime.size());
      for (java.util.List<java.lang.Integer> other_element : other.finishTime) {
        java.util.List<java.lang.Integer> __this__finishTime_copy = new java.util.ArrayList<java.lang.Integer>(other_element);
        __this__finishTime.add(__this__finishTime_copy);
      }
      this.finishTime = __this__finishTime;
    }
    if (other.isSetOutputSize()) {
      java.util.List<java.util.List<java.util.List<java.lang.Long>>> __this__outputSize = new java.util.ArrayList<java.util.List<java.util.List<java.lang.Long>>>(other.outputSize.size());
      for (java.util.List<java.util.List<java.lang.Long>> other_element : other.outputSize) {
        java.util.List<java.util.List<java.lang.Long>> __this__outputSize_copy = new java.util.ArrayList<java.util.List<java.lang.Long>>(other_element.size());
        for (java.util.List<java.lang.Long> other_element_element : other_element) {
          java.util.List<java.lang.Long> __this__outputSize_copy_copy = new java.util.ArrayList<java.lang.Long>(other_element_element);
          __this__outputSize_copy.add(__this__outputSize_copy_copy);
        }
        __this__outputSize.add(__this__outputSize_copy);
      }
      this.outputSize = __this__outputSize;
    }
    if (other.isSetSiteLoad()) {
      java.util.List<java.lang.Double> __this__siteLoad = new java.util.ArrayList<java.lang.Double>(other.siteLoad);
      this.siteLoad = __this__siteLoad;
    }
    if (other.isSetAssign()) {
      java.util.List<java.lang.Integer> __this__assign = new java.util.ArrayList<java.lang.Integer>(other.assign);
      this.assign = __this__assign;
    }
    this.alpha = other.alpha;
    if (other.isSetSiteSlots()) {
      java.util.List<java.lang.Integer> __this__siteSlots = new java.util.ArrayList<java.lang.Integer>(other.siteSlots);
      this.siteSlots = __this__siteSlots;
    }
  }

  public Request1 deepCopy() {
    return new Request1(this);
  }

  @Override
  public void clear() {
    setNumMappersIsSet(false);
    this.numMappers = 0;
    setNumReducersIsSet(false);
    this.numReducers = 0;
    setNumSitesIsSet(false);
    this.numSites = 0;
    this.bandwidth = null;
    this.finishTime = null;
    this.outputSize = null;
    this.siteLoad = null;
    this.assign = null;
    setAlphaIsSet(false);
    this.alpha = 0.0;
    this.siteSlots = null;
  }

  public int getNumMappers() {
    return this.numMappers;
  }

  public Request1 setNumMappers(int numMappers) {
    this.numMappers = numMappers;
    setNumMappersIsSet(true);
    return this;
  }

  public void unsetNumMappers() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __NUMMAPPERS_ISSET_ID);
  }

  /** Returns true if field numMappers is set (has been assigned a value) and false otherwise */
  public boolean isSetNumMappers() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __NUMMAPPERS_ISSET_ID);
  }

  public void setNumMappersIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __NUMMAPPERS_ISSET_ID, value);
  }

  public int getNumReducers() {
    return this.numReducers;
  }

  public Request1 setNumReducers(int numReducers) {
    this.numReducers = numReducers;
    setNumReducersIsSet(true);
    return this;
  }

  public void unsetNumReducers() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __NUMREDUCERS_ISSET_ID);
  }

  /** Returns true if field numReducers is set (has been assigned a value) and false otherwise */
  public boolean isSetNumReducers() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __NUMREDUCERS_ISSET_ID);
  }

  public void setNumReducersIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __NUMREDUCERS_ISSET_ID, value);
  }

  public int getNumSites() {
    return this.numSites;
  }

  public Request1 setNumSites(int numSites) {
    this.numSites = numSites;
    setNumSitesIsSet(true);
    return this;
  }

  public void unsetNumSites() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __NUMSITES_ISSET_ID);
  }

  /** Returns true if field numSites is set (has been assigned a value) and false otherwise */
  public boolean isSetNumSites() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __NUMSITES_ISSET_ID);
  }

  public void setNumSitesIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __NUMSITES_ISSET_ID, value);
  }

  public int getBandwidthSize() {
    return (this.bandwidth == null) ? 0 : this.bandwidth.size();
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Iterator<java.util.List<java.lang.Integer>> getBandwidthIterator() {
    return (this.bandwidth == null) ? null : this.bandwidth.iterator();
  }

  public void addToBandwidth(java.util.List<java.lang.Integer> elem) {
    if (this.bandwidth == null) {
      this.bandwidth = new java.util.ArrayList<java.util.List<java.lang.Integer>>();
    }
    this.bandwidth.add(elem);
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.List<java.util.List<java.lang.Integer>> getBandwidth() {
    return this.bandwidth;
  }

  public Request1 setBandwidth(@org.apache.thrift.annotation.Nullable java.util.List<java.util.List<java.lang.Integer>> bandwidth) {
    this.bandwidth = bandwidth;
    return this;
  }

  public void unsetBandwidth() {
    this.bandwidth = null;
  }

  /** Returns true if field bandwidth is set (has been assigned a value) and false otherwise */
  public boolean isSetBandwidth() {
    return this.bandwidth != null;
  }

  public void setBandwidthIsSet(boolean value) {
    if (!value) {
      this.bandwidth = null;
    }
  }

  public int getFinishTimeSize() {
    return (this.finishTime == null) ? 0 : this.finishTime.size();
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Iterator<java.util.List<java.lang.Integer>> getFinishTimeIterator() {
    return (this.finishTime == null) ? null : this.finishTime.iterator();
  }

  public void addToFinishTime(java.util.List<java.lang.Integer> elem) {
    if (this.finishTime == null) {
      this.finishTime = new java.util.ArrayList<java.util.List<java.lang.Integer>>();
    }
    this.finishTime.add(elem);
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.List<java.util.List<java.lang.Integer>> getFinishTime() {
    return this.finishTime;
  }

  public Request1 setFinishTime(@org.apache.thrift.annotation.Nullable java.util.List<java.util.List<java.lang.Integer>> finishTime) {
    this.finishTime = finishTime;
    return this;
  }

  public void unsetFinishTime() {
    this.finishTime = null;
  }

  /** Returns true if field finishTime is set (has been assigned a value) and false otherwise */
  public boolean isSetFinishTime() {
    return this.finishTime != null;
  }

  public void setFinishTimeIsSet(boolean value) {
    if (!value) {
      this.finishTime = null;
    }
  }

  public int getOutputSizeSize() {
    return (this.outputSize == null) ? 0 : this.outputSize.size();
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Iterator<java.util.List<java.util.List<java.lang.Long>>> getOutputSizeIterator() {
    return (this.outputSize == null) ? null : this.outputSize.iterator();
  }

  public void addToOutputSize(java.util.List<java.util.List<java.lang.Long>> elem) {
    if (this.outputSize == null) {
      this.outputSize = new java.util.ArrayList<java.util.List<java.util.List<java.lang.Long>>>();
    }
    this.outputSize.add(elem);
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.List<java.util.List<java.util.List<java.lang.Long>>> getOutputSize() {
    return this.outputSize;
  }

  public Request1 setOutputSize(@org.apache.thrift.annotation.Nullable java.util.List<java.util.List<java.util.List<java.lang.Long>>> outputSize) {
    this.outputSize = outputSize;
    return this;
  }

  public void unsetOutputSize() {
    this.outputSize = null;
  }

  /** Returns true if field outputSize is set (has been assigned a value) and false otherwise */
  public boolean isSetOutputSize() {
    return this.outputSize != null;
  }

  public void setOutputSizeIsSet(boolean value) {
    if (!value) {
      this.outputSize = null;
    }
  }

  public int getSiteLoadSize() {
    return (this.siteLoad == null) ? 0 : this.siteLoad.size();
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Iterator<java.lang.Double> getSiteLoadIterator() {
    return (this.siteLoad == null) ? null : this.siteLoad.iterator();
  }

  public void addToSiteLoad(double elem) {
    if (this.siteLoad == null) {
      this.siteLoad = new java.util.ArrayList<java.lang.Double>();
    }
    this.siteLoad.add(elem);
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.List<java.lang.Double> getSiteLoad() {
    return this.siteLoad;
  }

  public Request1 setSiteLoad(@org.apache.thrift.annotation.Nullable java.util.List<java.lang.Double> siteLoad) {
    this.siteLoad = siteLoad;
    return this;
  }

  public void unsetSiteLoad() {
    this.siteLoad = null;
  }

  /** Returns true if field siteLoad is set (has been assigned a value) and false otherwise */
  public boolean isSetSiteLoad() {
    return this.siteLoad != null;
  }

  public void setSiteLoadIsSet(boolean value) {
    if (!value) {
      this.siteLoad = null;
    }
  }

  public int getAssignSize() {
    return (this.assign == null) ? 0 : this.assign.size();
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Iterator<java.lang.Integer> getAssignIterator() {
    return (this.assign == null) ? null : this.assign.iterator();
  }

  public void addToAssign(int elem) {
    if (this.assign == null) {
      this.assign = new java.util.ArrayList<java.lang.Integer>();
    }
    this.assign.add(elem);
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.List<java.lang.Integer> getAssign() {
    return this.assign;
  }

  public Request1 setAssign(@org.apache.thrift.annotation.Nullable java.util.List<java.lang.Integer> assign) {
    this.assign = assign;
    return this;
  }

  public void unsetAssign() {
    this.assign = null;
  }

  /** Returns true if field assign is set (has been assigned a value) and false otherwise */
  public boolean isSetAssign() {
    return this.assign != null;
  }

  public void setAssignIsSet(boolean value) {
    if (!value) {
      this.assign = null;
    }
  }

  public double getAlpha() {
    return this.alpha;
  }

  public Request1 setAlpha(double alpha) {
    this.alpha = alpha;
    setAlphaIsSet(true);
    return this;
  }

  public void unsetAlpha() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __ALPHA_ISSET_ID);
  }

  /** Returns true if field alpha is set (has been assigned a value) and false otherwise */
  public boolean isSetAlpha() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __ALPHA_ISSET_ID);
  }

  public void setAlphaIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __ALPHA_ISSET_ID, value);
  }

  public int getSiteSlotsSize() {
    return (this.siteSlots == null) ? 0 : this.siteSlots.size();
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Iterator<java.lang.Integer> getSiteSlotsIterator() {
    return (this.siteSlots == null) ? null : this.siteSlots.iterator();
  }

  public void addToSiteSlots(int elem) {
    if (this.siteSlots == null) {
      this.siteSlots = new java.util.ArrayList<java.lang.Integer>();
    }
    this.siteSlots.add(elem);
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.List<java.lang.Integer> getSiteSlots() {
    return this.siteSlots;
  }

  public Request1 setSiteSlots(@org.apache.thrift.annotation.Nullable java.util.List<java.lang.Integer> siteSlots) {
    this.siteSlots = siteSlots;
    return this;
  }

  public void unsetSiteSlots() {
    this.siteSlots = null;
  }

  /** Returns true if field siteSlots is set (has been assigned a value) and false otherwise */
  public boolean isSetSiteSlots() {
    return this.siteSlots != null;
  }

  public void setSiteSlotsIsSet(boolean value) {
    if (!value) {
      this.siteSlots = null;
    }
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case NUM_MAPPERS:
      if (value == null) {
        unsetNumMappers();
      } else {
        setNumMappers((java.lang.Integer)value);
      }
      break;

    case NUM_REDUCERS:
      if (value == null) {
        unsetNumReducers();
      } else {
        setNumReducers((java.lang.Integer)value);
      }
      break;

    case NUM_SITES:
      if (value == null) {
        unsetNumSites();
      } else {
        setNumSites((java.lang.Integer)value);
      }
      break;

    case BANDWIDTH:
      if (value == null) {
        unsetBandwidth();
      } else {
        setBandwidth((java.util.List<java.util.List<java.lang.Integer>>)value);
      }
      break;

    case FINISH_TIME:
      if (value == null) {
        unsetFinishTime();
      } else {
        setFinishTime((java.util.List<java.util.List<java.lang.Integer>>)value);
      }
      break;

    case OUTPUT_SIZE:
      if (value == null) {
        unsetOutputSize();
      } else {
        setOutputSize((java.util.List<java.util.List<java.util.List<java.lang.Long>>>)value);
      }
      break;

    case SITE_LOAD:
      if (value == null) {
        unsetSiteLoad();
      } else {
        setSiteLoad((java.util.List<java.lang.Double>)value);
      }
      break;

    case ASSIGN:
      if (value == null) {
        unsetAssign();
      } else {
        setAssign((java.util.List<java.lang.Integer>)value);
      }
      break;

    case ALPHA:
      if (value == null) {
        unsetAlpha();
      } else {
        setAlpha((java.lang.Double)value);
      }
      break;

    case SITE_SLOTS:
      if (value == null) {
        unsetSiteSlots();
      } else {
        setSiteSlots((java.util.List<java.lang.Integer>)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case NUM_MAPPERS:
      return getNumMappers();

    case NUM_REDUCERS:
      return getNumReducers();

    case NUM_SITES:
      return getNumSites();

    case BANDWIDTH:
      return getBandwidth();

    case FINISH_TIME:
      return getFinishTime();

    case OUTPUT_SIZE:
      return getOutputSize();

    case SITE_LOAD:
      return getSiteLoad();

    case ASSIGN:
      return getAssign();

    case ALPHA:
      return getAlpha();

    case SITE_SLOTS:
      return getSiteSlots();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case NUM_MAPPERS:
      return isSetNumMappers();
    case NUM_REDUCERS:
      return isSetNumReducers();
    case NUM_SITES:
      return isSetNumSites();
    case BANDWIDTH:
      return isSetBandwidth();
    case FINISH_TIME:
      return isSetFinishTime();
    case OUTPUT_SIZE:
      return isSetOutputSize();
    case SITE_LOAD:
      return isSetSiteLoad();
    case ASSIGN:
      return isSetAssign();
    case ALPHA:
      return isSetAlpha();
    case SITE_SLOTS:
      return isSetSiteSlots();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof Request1)
      return this.equals((Request1)that);
    return false;
  }

  public boolean equals(Request1 that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_numMappers = true;
    boolean that_present_numMappers = true;
    if (this_present_numMappers || that_present_numMappers) {
      if (!(this_present_numMappers && that_present_numMappers))
        return false;
      if (this.numMappers != that.numMappers)
        return false;
    }

    boolean this_present_numReducers = true;
    boolean that_present_numReducers = true;
    if (this_present_numReducers || that_present_numReducers) {
      if (!(this_present_numReducers && that_present_numReducers))
        return false;
      if (this.numReducers != that.numReducers)
        return false;
    }

    boolean this_present_numSites = true;
    boolean that_present_numSites = true;
    if (this_present_numSites || that_present_numSites) {
      if (!(this_present_numSites && that_present_numSites))
        return false;
      if (this.numSites != that.numSites)
        return false;
    }

    boolean this_present_bandwidth = true && this.isSetBandwidth();
    boolean that_present_bandwidth = true && that.isSetBandwidth();
    if (this_present_bandwidth || that_present_bandwidth) {
      if (!(this_present_bandwidth && that_present_bandwidth))
        return false;
      if (!this.bandwidth.equals(that.bandwidth))
        return false;
    }

    boolean this_present_finishTime = true && this.isSetFinishTime();
    boolean that_present_finishTime = true && that.isSetFinishTime();
    if (this_present_finishTime || that_present_finishTime) {
      if (!(this_present_finishTime && that_present_finishTime))
        return false;
      if (!this.finishTime.equals(that.finishTime))
        return false;
    }

    boolean this_present_outputSize = true && this.isSetOutputSize();
    boolean that_present_outputSize = true && that.isSetOutputSize();
    if (this_present_outputSize || that_present_outputSize) {
      if (!(this_present_outputSize && that_present_outputSize))
        return false;
      if (!this.outputSize.equals(that.outputSize))
        return false;
    }

    boolean this_present_siteLoad = true && this.isSetSiteLoad();
    boolean that_present_siteLoad = true && that.isSetSiteLoad();
    if (this_present_siteLoad || that_present_siteLoad) {
      if (!(this_present_siteLoad && that_present_siteLoad))
        return false;
      if (!this.siteLoad.equals(that.siteLoad))
        return false;
    }

    boolean this_present_assign = true && this.isSetAssign();
    boolean that_present_assign = true && that.isSetAssign();
    if (this_present_assign || that_present_assign) {
      if (!(this_present_assign && that_present_assign))
        return false;
      if (!this.assign.equals(that.assign))
        return false;
    }

    boolean this_present_alpha = true;
    boolean that_present_alpha = true;
    if (this_present_alpha || that_present_alpha) {
      if (!(this_present_alpha && that_present_alpha))
        return false;
      if (this.alpha != that.alpha)
        return false;
    }

    boolean this_present_siteSlots = true && this.isSetSiteSlots();
    boolean that_present_siteSlots = true && that.isSetSiteSlots();
    if (this_present_siteSlots || that_present_siteSlots) {
      if (!(this_present_siteSlots && that_present_siteSlots))
        return false;
      if (!this.siteSlots.equals(that.siteSlots))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + numMappers;

    hashCode = hashCode * 8191 + numReducers;

    hashCode = hashCode * 8191 + numSites;

    hashCode = hashCode * 8191 + ((isSetBandwidth()) ? 131071 : 524287);
    if (isSetBandwidth())
      hashCode = hashCode * 8191 + bandwidth.hashCode();

    hashCode = hashCode * 8191 + ((isSetFinishTime()) ? 131071 : 524287);
    if (isSetFinishTime())
      hashCode = hashCode * 8191 + finishTime.hashCode();

    hashCode = hashCode * 8191 + ((isSetOutputSize()) ? 131071 : 524287);
    if (isSetOutputSize())
      hashCode = hashCode * 8191 + outputSize.hashCode();

    hashCode = hashCode * 8191 + ((isSetSiteLoad()) ? 131071 : 524287);
    if (isSetSiteLoad())
      hashCode = hashCode * 8191 + siteLoad.hashCode();

    hashCode = hashCode * 8191 + ((isSetAssign()) ? 131071 : 524287);
    if (isSetAssign())
      hashCode = hashCode * 8191 + assign.hashCode();

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(alpha);

    hashCode = hashCode * 8191 + ((isSetSiteSlots()) ? 131071 : 524287);
    if (isSetSiteSlots())
      hashCode = hashCode * 8191 + siteSlots.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(Request1 other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetNumMappers(), other.isSetNumMappers());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetNumMappers()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.numMappers, other.numMappers);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetNumReducers(), other.isSetNumReducers());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetNumReducers()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.numReducers, other.numReducers);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetNumSites(), other.isSetNumSites());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetNumSites()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.numSites, other.numSites);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetBandwidth(), other.isSetBandwidth());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetBandwidth()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.bandwidth, other.bandwidth);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetFinishTime(), other.isSetFinishTime());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetFinishTime()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.finishTime, other.finishTime);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetOutputSize(), other.isSetOutputSize());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOutputSize()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.outputSize, other.outputSize);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetSiteLoad(), other.isSetSiteLoad());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSiteLoad()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.siteLoad, other.siteLoad);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetAssign(), other.isSetAssign());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAssign()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.assign, other.assign);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetAlpha(), other.isSetAlpha());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAlpha()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.alpha, other.alpha);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetSiteSlots(), other.isSetSiteSlots());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSiteSlots()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.siteSlots, other.siteSlots);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("Request1(");
    boolean first = true;

    sb.append("numMappers:");
    sb.append(this.numMappers);
    first = false;
    if (!first) sb.append(", ");
    sb.append("numReducers:");
    sb.append(this.numReducers);
    first = false;
    if (!first) sb.append(", ");
    sb.append("numSites:");
    sb.append(this.numSites);
    first = false;
    if (isSetBandwidth()) {
      if (!first) sb.append(", ");
      sb.append("bandwidth:");
      if (this.bandwidth == null) {
        sb.append("null");
      } else {
        sb.append(this.bandwidth);
      }
      first = false;
    }
    if (isSetFinishTime()) {
      if (!first) sb.append(", ");
      sb.append("finishTime:");
      if (this.finishTime == null) {
        sb.append("null");
      } else {
        sb.append(this.finishTime);
      }
      first = false;
    }
    if (isSetOutputSize()) {
      if (!first) sb.append(", ");
      sb.append("outputSize:");
      if (this.outputSize == null) {
        sb.append("null");
      } else {
        sb.append(this.outputSize);
      }
      first = false;
    }
    if (isSetSiteLoad()) {
      if (!first) sb.append(", ");
      sb.append("siteLoad:");
      if (this.siteLoad == null) {
        sb.append("null");
      } else {
        sb.append(this.siteLoad);
      }
      first = false;
    }
    if (isSetAssign()) {
      if (!first) sb.append(", ");
      sb.append("assign:");
      if (this.assign == null) {
        sb.append("null");
      } else {
        sb.append(this.assign);
      }
      first = false;
    }
    if (!first) sb.append(", ");
    sb.append("alpha:");
    sb.append(this.alpha);
    first = false;
    if (!first) sb.append(", ");
    sb.append("siteSlots:");
    if (this.siteSlots == null) {
      sb.append("null");
    } else {
      sb.append(this.siteSlots);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // alas, we cannot check 'numMappers' because it's a primitive and you chose the non-beans generator.
    // alas, we cannot check 'numReducers' because it's a primitive and you chose the non-beans generator.
    // alas, we cannot check 'numSites' because it's a primitive and you chose the non-beans generator.
    // alas, we cannot check 'alpha' because it's a primitive and you chose the non-beans generator.
    if (siteSlots == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'siteSlots' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class Request1StandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public Request1StandardScheme getScheme() {
      return new Request1StandardScheme();
    }
  }

  private static class Request1StandardScheme extends org.apache.thrift.scheme.StandardScheme<Request1> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, Request1 struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // NUM_MAPPERS
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.numMappers = iprot.readI32();
              struct.setNumMappersIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // NUM_REDUCERS
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.numReducers = iprot.readI32();
              struct.setNumReducersIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // NUM_SITES
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.numSites = iprot.readI32();
              struct.setNumSitesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // BANDWIDTH
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list0 = iprot.readListBegin();
                struct.bandwidth = new java.util.ArrayList<java.util.List<java.lang.Integer>>(_list0.size);
                @org.apache.thrift.annotation.Nullable java.util.List<java.lang.Integer> _elem1;
                for (int _i2 = 0; _i2 < _list0.size; ++_i2)
                {
                  {
                    org.apache.thrift.protocol.TList _list3 = iprot.readListBegin();
                    _elem1 = new java.util.ArrayList<java.lang.Integer>(_list3.size);
                    int _elem4;
                    for (int _i5 = 0; _i5 < _list3.size; ++_i5)
                    {
                      _elem4 = iprot.readI32();
                      _elem1.add(_elem4);
                    }
                    iprot.readListEnd();
                  }
                  struct.bandwidth.add(_elem1);
                }
                iprot.readListEnd();
              }
              struct.setBandwidthIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // FINISH_TIME
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list6 = iprot.readListBegin();
                struct.finishTime = new java.util.ArrayList<java.util.List<java.lang.Integer>>(_list6.size);
                @org.apache.thrift.annotation.Nullable java.util.List<java.lang.Integer> _elem7;
                for (int _i8 = 0; _i8 < _list6.size; ++_i8)
                {
                  {
                    org.apache.thrift.protocol.TList _list9 = iprot.readListBegin();
                    _elem7 = new java.util.ArrayList<java.lang.Integer>(_list9.size);
                    int _elem10;
                    for (int _i11 = 0; _i11 < _list9.size; ++_i11)
                    {
                      _elem10 = iprot.readI32();
                      _elem7.add(_elem10);
                    }
                    iprot.readListEnd();
                  }
                  struct.finishTime.add(_elem7);
                }
                iprot.readListEnd();
              }
              struct.setFinishTimeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // OUTPUT_SIZE
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list12 = iprot.readListBegin();
                struct.outputSize = new java.util.ArrayList<java.util.List<java.util.List<java.lang.Long>>>(_list12.size);
                @org.apache.thrift.annotation.Nullable java.util.List<java.util.List<java.lang.Long>> _elem13;
                for (int _i14 = 0; _i14 < _list12.size; ++_i14)
                {
                  {
                    org.apache.thrift.protocol.TList _list15 = iprot.readListBegin();
                    _elem13 = new java.util.ArrayList<java.util.List<java.lang.Long>>(_list15.size);
                    @org.apache.thrift.annotation.Nullable java.util.List<java.lang.Long> _elem16;
                    for (int _i17 = 0; _i17 < _list15.size; ++_i17)
                    {
                      {
                        org.apache.thrift.protocol.TList _list18 = iprot.readListBegin();
                        _elem16 = new java.util.ArrayList<java.lang.Long>(_list18.size);
                        long _elem19;
                        for (int _i20 = 0; _i20 < _list18.size; ++_i20)
                        {
                          _elem19 = iprot.readI64();
                          _elem16.add(_elem19);
                        }
                        iprot.readListEnd();
                      }
                      _elem13.add(_elem16);
                    }
                    iprot.readListEnd();
                  }
                  struct.outputSize.add(_elem13);
                }
                iprot.readListEnd();
              }
              struct.setOutputSizeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // SITE_LOAD
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list21 = iprot.readListBegin();
                struct.siteLoad = new java.util.ArrayList<java.lang.Double>(_list21.size);
                double _elem22;
                for (int _i23 = 0; _i23 < _list21.size; ++_i23)
                {
                  _elem22 = iprot.readDouble();
                  struct.siteLoad.add(_elem22);
                }
                iprot.readListEnd();
              }
              struct.setSiteLoadIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 8: // ASSIGN
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list24 = iprot.readListBegin();
                struct.assign = new java.util.ArrayList<java.lang.Integer>(_list24.size);
                int _elem25;
                for (int _i26 = 0; _i26 < _list24.size; ++_i26)
                {
                  _elem25 = iprot.readI32();
                  struct.assign.add(_elem25);
                }
                iprot.readListEnd();
              }
              struct.setAssignIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 9: // ALPHA
            if (schemeField.type == org.apache.thrift.protocol.TType.DOUBLE) {
              struct.alpha = iprot.readDouble();
              struct.setAlphaIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 10: // SITE_SLOTS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list27 = iprot.readListBegin();
                struct.siteSlots = new java.util.ArrayList<java.lang.Integer>(_list27.size);
                int _elem28;
                for (int _i29 = 0; _i29 < _list27.size; ++_i29)
                {
                  _elem28 = iprot.readI32();
                  struct.siteSlots.add(_elem28);
                }
                iprot.readListEnd();
              }
              struct.setSiteSlotsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetNumMappers()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'numMappers' was not found in serialized data! Struct: " + toString());
      }
      if (!struct.isSetNumReducers()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'numReducers' was not found in serialized data! Struct: " + toString());
      }
      if (!struct.isSetNumSites()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'numSites' was not found in serialized data! Struct: " + toString());
      }
      if (!struct.isSetAlpha()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'alpha' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, Request1 struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(NUM_MAPPERS_FIELD_DESC);
      oprot.writeI32(struct.numMappers);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(NUM_REDUCERS_FIELD_DESC);
      oprot.writeI32(struct.numReducers);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(NUM_SITES_FIELD_DESC);
      oprot.writeI32(struct.numSites);
      oprot.writeFieldEnd();
      if (struct.bandwidth != null) {
        if (struct.isSetBandwidth()) {
          oprot.writeFieldBegin(BANDWIDTH_FIELD_DESC);
          {
            oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.LIST, struct.bandwidth.size()));
            for (java.util.List<java.lang.Integer> _iter30 : struct.bandwidth)
            {
              {
                oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.I32, _iter30.size()));
                for (int _iter31 : _iter30)
                {
                  oprot.writeI32(_iter31);
                }
                oprot.writeListEnd();
              }
            }
            oprot.writeListEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      if (struct.finishTime != null) {
        if (struct.isSetFinishTime()) {
          oprot.writeFieldBegin(FINISH_TIME_FIELD_DESC);
          {
            oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.LIST, struct.finishTime.size()));
            for (java.util.List<java.lang.Integer> _iter32 : struct.finishTime)
            {
              {
                oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.I32, _iter32.size()));
                for (int _iter33 : _iter32)
                {
                  oprot.writeI32(_iter33);
                }
                oprot.writeListEnd();
              }
            }
            oprot.writeListEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      if (struct.outputSize != null) {
        if (struct.isSetOutputSize()) {
          oprot.writeFieldBegin(OUTPUT_SIZE_FIELD_DESC);
          {
            oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.LIST, struct.outputSize.size()));
            for (java.util.List<java.util.List<java.lang.Long>> _iter34 : struct.outputSize)
            {
              {
                oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.LIST, _iter34.size()));
                for (java.util.List<java.lang.Long> _iter35 : _iter34)
                {
                  {
                    oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.I64, _iter35.size()));
                    for (long _iter36 : _iter35)
                    {
                      oprot.writeI64(_iter36);
                    }
                    oprot.writeListEnd();
                  }
                }
                oprot.writeListEnd();
              }
            }
            oprot.writeListEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      if (struct.siteLoad != null) {
        if (struct.isSetSiteLoad()) {
          oprot.writeFieldBegin(SITE_LOAD_FIELD_DESC);
          {
            oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.DOUBLE, struct.siteLoad.size()));
            for (double _iter37 : struct.siteLoad)
            {
              oprot.writeDouble(_iter37);
            }
            oprot.writeListEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      if (struct.assign != null) {
        if (struct.isSetAssign()) {
          oprot.writeFieldBegin(ASSIGN_FIELD_DESC);
          {
            oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.I32, struct.assign.size()));
            for (int _iter38 : struct.assign)
            {
              oprot.writeI32(_iter38);
            }
            oprot.writeListEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldBegin(ALPHA_FIELD_DESC);
      oprot.writeDouble(struct.alpha);
      oprot.writeFieldEnd();
      if (struct.siteSlots != null) {
        oprot.writeFieldBegin(SITE_SLOTS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.I32, struct.siteSlots.size()));
          for (int _iter39 : struct.siteSlots)
          {
            oprot.writeI32(_iter39);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class Request1TupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public Request1TupleScheme getScheme() {
      return new Request1TupleScheme();
    }
  }

  private static class Request1TupleScheme extends org.apache.thrift.scheme.TupleScheme<Request1> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, Request1 struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      oprot.writeI32(struct.numMappers);
      oprot.writeI32(struct.numReducers);
      oprot.writeI32(struct.numSites);
      oprot.writeDouble(struct.alpha);
      {
        oprot.writeI32(struct.siteSlots.size());
        for (int _iter40 : struct.siteSlots)
        {
          oprot.writeI32(_iter40);
        }
      }
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetBandwidth()) {
        optionals.set(0);
      }
      if (struct.isSetFinishTime()) {
        optionals.set(1);
      }
      if (struct.isSetOutputSize()) {
        optionals.set(2);
      }
      if (struct.isSetSiteLoad()) {
        optionals.set(3);
      }
      if (struct.isSetAssign()) {
        optionals.set(4);
      }
      oprot.writeBitSet(optionals, 5);
      if (struct.isSetBandwidth()) {
        {
          oprot.writeI32(struct.bandwidth.size());
          for (java.util.List<java.lang.Integer> _iter41 : struct.bandwidth)
          {
            {
              oprot.writeI32(_iter41.size());
              for (int _iter42 : _iter41)
              {
                oprot.writeI32(_iter42);
              }
            }
          }
        }
      }
      if (struct.isSetFinishTime()) {
        {
          oprot.writeI32(struct.finishTime.size());
          for (java.util.List<java.lang.Integer> _iter43 : struct.finishTime)
          {
            {
              oprot.writeI32(_iter43.size());
              for (int _iter44 : _iter43)
              {
                oprot.writeI32(_iter44);
              }
            }
          }
        }
      }
      if (struct.isSetOutputSize()) {
        {
          oprot.writeI32(struct.outputSize.size());
          for (java.util.List<java.util.List<java.lang.Long>> _iter45 : struct.outputSize)
          {
            {
              oprot.writeI32(_iter45.size());
              for (java.util.List<java.lang.Long> _iter46 : _iter45)
              {
                {
                  oprot.writeI32(_iter46.size());
                  for (long _iter47 : _iter46)
                  {
                    oprot.writeI64(_iter47);
                  }
                }
              }
            }
          }
        }
      }
      if (struct.isSetSiteLoad()) {
        {
          oprot.writeI32(struct.siteLoad.size());
          for (double _iter48 : struct.siteLoad)
          {
            oprot.writeDouble(_iter48);
          }
        }
      }
      if (struct.isSetAssign()) {
        {
          oprot.writeI32(struct.assign.size());
          for (int _iter49 : struct.assign)
          {
            oprot.writeI32(_iter49);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, Request1 struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      struct.numMappers = iprot.readI32();
      struct.setNumMappersIsSet(true);
      struct.numReducers = iprot.readI32();
      struct.setNumReducersIsSet(true);
      struct.numSites = iprot.readI32();
      struct.setNumSitesIsSet(true);
      struct.alpha = iprot.readDouble();
      struct.setAlphaIsSet(true);
      {
        org.apache.thrift.protocol.TList _list50 = iprot.readListBegin(org.apache.thrift.protocol.TType.I32);
        struct.siteSlots = new java.util.ArrayList<java.lang.Integer>(_list50.size);
        int _elem51;
        for (int _i52 = 0; _i52 < _list50.size; ++_i52)
        {
          _elem51 = iprot.readI32();
          struct.siteSlots.add(_elem51);
        }
      }
      struct.setSiteSlotsIsSet(true);
      java.util.BitSet incoming = iprot.readBitSet(5);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TList _list53 = iprot.readListBegin(org.apache.thrift.protocol.TType.LIST);
          struct.bandwidth = new java.util.ArrayList<java.util.List<java.lang.Integer>>(_list53.size);
          @org.apache.thrift.annotation.Nullable java.util.List<java.lang.Integer> _elem54;
          for (int _i55 = 0; _i55 < _list53.size; ++_i55)
          {
            {
              org.apache.thrift.protocol.TList _list56 = iprot.readListBegin(org.apache.thrift.protocol.TType.I32);
              _elem54 = new java.util.ArrayList<java.lang.Integer>(_list56.size);
              int _elem57;
              for (int _i58 = 0; _i58 < _list56.size; ++_i58)
              {
                _elem57 = iprot.readI32();
                _elem54.add(_elem57);
              }
            }
            struct.bandwidth.add(_elem54);
          }
        }
        struct.setBandwidthIsSet(true);
      }
      if (incoming.get(1)) {
        {
          org.apache.thrift.protocol.TList _list59 = iprot.readListBegin(org.apache.thrift.protocol.TType.LIST);
          struct.finishTime = new java.util.ArrayList<java.util.List<java.lang.Integer>>(_list59.size);
          @org.apache.thrift.annotation.Nullable java.util.List<java.lang.Integer> _elem60;
          for (int _i61 = 0; _i61 < _list59.size; ++_i61)
          {
            {
              org.apache.thrift.protocol.TList _list62 = iprot.readListBegin(org.apache.thrift.protocol.TType.I32);
              _elem60 = new java.util.ArrayList<java.lang.Integer>(_list62.size);
              int _elem63;
              for (int _i64 = 0; _i64 < _list62.size; ++_i64)
              {
                _elem63 = iprot.readI32();
                _elem60.add(_elem63);
              }
            }
            struct.finishTime.add(_elem60);
          }
        }
        struct.setFinishTimeIsSet(true);
      }
      if (incoming.get(2)) {
        {
          org.apache.thrift.protocol.TList _list65 = iprot.readListBegin(org.apache.thrift.protocol.TType.LIST);
          struct.outputSize = new java.util.ArrayList<java.util.List<java.util.List<java.lang.Long>>>(_list65.size);
          @org.apache.thrift.annotation.Nullable java.util.List<java.util.List<java.lang.Long>> _elem66;
          for (int _i67 = 0; _i67 < _list65.size; ++_i67)
          {
            {
              org.apache.thrift.protocol.TList _list68 = iprot.readListBegin(org.apache.thrift.protocol.TType.LIST);
              _elem66 = new java.util.ArrayList<java.util.List<java.lang.Long>>(_list68.size);
              @org.apache.thrift.annotation.Nullable java.util.List<java.lang.Long> _elem69;
              for (int _i70 = 0; _i70 < _list68.size; ++_i70)
              {
                {
                  org.apache.thrift.protocol.TList _list71 = iprot.readListBegin(org.apache.thrift.protocol.TType.I64);
                  _elem69 = new java.util.ArrayList<java.lang.Long>(_list71.size);
                  long _elem72;
                  for (int _i73 = 0; _i73 < _list71.size; ++_i73)
                  {
                    _elem72 = iprot.readI64();
                    _elem69.add(_elem72);
                  }
                }
                _elem66.add(_elem69);
              }
            }
            struct.outputSize.add(_elem66);
          }
        }
        struct.setOutputSizeIsSet(true);
      }
      if (incoming.get(3)) {
        {
          org.apache.thrift.protocol.TList _list74 = iprot.readListBegin(org.apache.thrift.protocol.TType.DOUBLE);
          struct.siteLoad = new java.util.ArrayList<java.lang.Double>(_list74.size);
          double _elem75;
          for (int _i76 = 0; _i76 < _list74.size; ++_i76)
          {
            _elem75 = iprot.readDouble();
            struct.siteLoad.add(_elem75);
          }
        }
        struct.setSiteLoadIsSet(true);
      }
      if (incoming.get(4)) {
        {
          org.apache.thrift.protocol.TList _list77 = iprot.readListBegin(org.apache.thrift.protocol.TType.I32);
          struct.assign = new java.util.ArrayList<java.lang.Integer>(_list77.size);
          int _elem78;
          for (int _i79 = 0; _i79 < _list77.size; ++_i79)
          {
            _elem78 = iprot.readI32();
            struct.assign.add(_elem78);
          }
        }
        struct.setAssignIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

